### ISSUE TITLE
document/caution where bash subshell limitation affects event api?

### ISSUE THREAD

**Issue by abathur** [bashup/events#2]
I bumped into a bash limitation that might be worth documenting where it impacts the event api.

 Some features break down when run in a subshell:

    bash-5.0$ event once bah echo bah
    bash-5.0$ echo $(event emit bah)
    bah
    bash-5.0$ echo $(event emit bah)
    bah

I assume it also affects `fire` and by proxy `resolve`.

**Comment by pjeby** [comment]
That's a good point.  I sort of assumed it because, well, that's how bash variables work.  I'll have to figure out where to put it, but maybe something like:

> ### Events and Subshells
>
> Just like bash variables and functions, the event system state cannot be altered from a subshell, although a subshell inherits the current event system state.  This means that adding or removing handlers in subshell (even *implicitly*, via `fire`, `resolve`, `once`, etc.) has no effect on the calling shell.  As is normally the case for subshells, you'll need to read their output and act on it, if you need side-effects in the parent shell.

...would work?

**Comment by abathur** [comment]
I think that covers it. I knew what it was as soon as I saw it, but I don't know how common the knowledge is overall.

**Comment by pjeby** [comment]
Closed via 85194da  and 9fbd9f6.
